(function(c){SLB={prefix:"slb",options:{},trigger:null,urls_checked:{},items:[],item_curr:null,item_init:null,group:null,media:{},content:{caption_enabled:true,caption_src:true,desc_enabled:true,labels:{closeLink:"close",loadingMsg:"loading",nextLink:"next &raquo;",prevLink:"&laquo; prev",startSlideshow:"start slideshow",stopSlideshow:"stop slideshow",numDisplayPrefix:"Image",numDisplaySeparator:"of"}},container:document,masks:["select","object","embed","iframe"],layout:{template:"",parsed:"",placeholders:{slbContent:'<img id="slb_slbContent" />',
slbLoading:'<span id="slb_slbLoading">loading</span>',slbClose:'<a class="slb_slbClose" href="#">close</a>',navPrev:'<a class="slb_navPrev slb_nav" href="#">&laquo; prev</a>',navNext:'<a class="slb_navNext slb_nav" href="#">&raquo; next</a>',navSlideControl:'<a class="slb_navSlideControl" href="#">Stop</a>',dataCaption:'<span class="slb_dataCaption"></span>',dataDescription:'<span class="slb_dataDescription"></span>',dataNumber:'<span class="slb_dataNumber"></span>'}},slideshow:{active:null,enabled:true,
loop:true,duration:4,timer:null},anim:{active:true,overlay_duration:0,overlay_opacity:0.8,resize_duration:0},init:function(a){this.options=c.extend(true,{prefix:null,trigger:null,validateLinks:false,captionEnabled:true,captionSrc:true,descEnabled:true,labels:{},layout:null,placeholders:{},animate:true,overlayDuration:0.2,overlayOpacity:0.8,resizeSpeed:400,autoPlay:true,enableSlideshow:true,loop:true,slideTime:4},a);if(!this.options.layout||this.options.layout.toString().length==0)this.end();if(c.type(this.options.prefix)==
"string"&&this.options.prefix.length>0)this.prefix=this.options.prefix;if(!c.isArray(this.options.trigger))this.trigger=[this.prefix];c.extend(true,this.content,{caption_enabled:!!this.options.captionEnabled,caption_src:!!this.options.captionSrc,desc_enabled:!!this.options.descEnabled,labels:c.isPlainObject(this.options.labels)?this.options.labels:{}});c.extend(true,this.layout,{template:this.options.layout,placeholders:this.options.placeholders});c.extend(this.anim,{overlay_opacity:Math.max(Math.min(this.options.overlayOpacity,
1),0)});this.options.animate?c.extend(this.anim,{active:true,overlay_duration:Math.max(this.options.overlayDuration,0),resize_duration:this.options.resizeSpeed}):c.extend(this.anim,{active:false,overlay_duration:0,resize_duration:0});c.extend(this.slideshow,{play:!!this.options.autoPlay,enabled:!!this.options.enableSlideshow,loop:!!this.options.enableSlideshow&&!!this.options.loop,duration:c.isNumeric(this.options.slideTime)?parseInt(this.options.slideTime):0});var b=this;a=c("body");c("<div/>",{id:this.getID("overlay"),
css:{display:"none"}}).appendTo(a).click(function(){b.end()});a=c("<div/>",{id:this.getID("viewer"),css:{display:"none"}}).appendTo(a).click(function(){b.end()});this.layout.parsed=this.getLayout();c(this.layout.parsed).appendTo(a);this.initUI();this.initEvents()},initUI:function(){this.get("slbClose").html(this.getLabel("closeLink"));this.get("navNext").html(this.getLabel("nextLink"));this.get("navPrev").html(this.getLabel("prevLink"));this.get("navSlideControl").html(this.getLabel(this.slideshowActive()?
"stopSlideshow":"startSlideshow"))},initEvents:function(){var a=this;this.get("container,details,navPrev,navNext,navSlideControl,slbClose").unbind("click");this.get("container,details").click(function(e){e.stopPropagation()});var b=function(){a.get("navPrev").unbind("click").click(false);setTimeout(function(){a.get("navPrev").click(b)},500);a.navPrev();return false};this.get("navPrev").click(function(){return b()});var d=function(){a.get("navNext").unbind("click").click(false);setTimeout(function(){a.get("navNext").click(d)},
500);a.navNext();return false};this.get("navNext").click(function(){return d()});this.get("navSlideControl").click(function(){a.slideshowToggle();return false});this.get("slbClose").click(function(){a.end();return false});this.initLinks()},initLinks:function(){for(var a=this,b=[],d='a[href][rel*="{relattr}"]:not([rel~="'+this.addPrefix("off")+'"])',e=0;e<this.trigger.length;e++)b.push(d.replace("{relattr}",this.trigger[e]));b=b.join(",");c(b,c(this.container)).live("click",function(){a.view(this);
return false})},view:function(a){a=c(a);this.mask();this.items=[];this.setGroup(a);var b=this,d={};this.fileExists(this.itemSource(a),function(){var e=function(){b.item_init=0;var f=[],m;for(var l in d)f.push(l);f.sort(function(n,o){return n-o});for(l=0;l<f.length;l++){m=d[f[l]];if(c(m).get(0)==c(a).get(0))b.item_init=l;b.items.push({link:b.itemSource(c(m)),title:b.getCaption(m),desc:b.getDescription(m)})}f=c(document).scrollTop()+c(window).height()/15;b.get("viewer").css("top",f+"px").show();b.itemLoad(b.item_init)};
b.get("overlay").height(c(document).height()).fadeTo(b.anim.overlay_duration,b.options.overlayOpacity);if(b.hasGroup()){var k=c(b.container).find("a"),g=[],h,j;for(h=0;h<k.length;h++){j=c(k[h]);b.itemSource(j)&&b.inGroup(j)&&g.push(j)}var i=0;for(h=0;h<g.length;h++){j=g[h];b.fileExists(b.itemSource(c(j)),function(f){d[f.idx]=f.items[f.idx];i++;i==f.items.length&&e()},function(f){i++;f.idx==f.items.length&&e()},{idx:h,items:g})}}else{b.item_init=0;d[b.item_init]=a;e()}},function(){b.end()})},end:function(){this.keyboardDisable();
this.slideshowPause();this.get("viewer").hide();this.get("overlay").fadeOut(this.anim.overlay_duration);this.unmask()},viewerResize:function(a,b){var d=this.viewerSize(a,b);this.get("container").animate({width:d.width,height:d.height},this.anim.resize_duration);this.get("overlay").css("min-width",d.width);this.itemShow()},viewerSize:function(a,b){for(var d=["left","right"],e=["top","bottom"],k=0,g=0,h=this,j=function(f){f=h.get("content").css("padding-"+f);f=f.indexOf("px")==-1?0:f.replace("px","");
return c.isNumeric(f)?parseFloat(f):0},i=0;i<d.length;i++)k+=j(d[i]);for(i=0;i<e.length;i++)g+=j(e[i]);return{width:a+k,height:b+g}},unmask:function(a){c(this.masks.join(",")).css("visibility",(typeof a=="undefined"?true:!!a)?"visible":"hidden")},mask:function(){this.unmask(false)},itemProp:function(a,b){return a<this.items.length&&b in this.items[a]?this.items[a][b]:""},itemLoad:function(a){this.item_curr=a;this.keyboardDisable();this.slideshowPause();this.get("slbLoading").show();this.get("slbContent").hide();
this.get("details").hide();var b=new Image,d=this;c(b).bind("load",function(){d.get("slbContent").attr("src",b.src);d.viewerResize(b.width,b.height);d.slideshowActive()&&d.slideshowStart()});b.src=this.itemProp(this.item_curr,"link")},itemShow:function(){this.get("slbLoading").hide();var a=this;this.get("slbContent").fadeIn(500,function(){a.contentUpdate()});this.hasItems()&&this.itemPreloadSiblings()},itemPreloadSiblings:function(){var a=this.itemFirst()?this.items.length-1:this.item_curr-1;(new Image).src=
this.itemProp(a,"link");var b=this.itemLast()?0:this.item_curr+1;if(b!=a)(new Image).src=this.itemProp(b,"link")},hasItem:function(){return this.items.length>0},hasItems:function(){return this.items.length>1},itemFirst:function(){return this.item_curr==0},itemLast:function(){return this.item_curr==this.items.length-1},itemSource:function(a){var b=c(a).attr("href");if((c(a).attr("rel")||"").length){a=this.mediaProp(a,"source");if(c.type(a)==="string"&&a.length)b=a}return b},itemGallery:function(a,
b){var d={wp:".gallery-icon",ng:".ngg-gallery-thumbnail"};if(typeof b=="undefined"||!(b in d))b="wp";return c(a).parent(d[b]).length>0?true:false},mediaId:function(a){a=c(a).attr("href");if(c.type(a)!=="string")a=false;return a},mediaProps:function(a){var b={};if((a=this.mediaId(a))&&a in this.media)b=this.media[a];return b},mediaProp:function(a,b){var d=this.mediaProps(a);return b in d?d[b]:null},getLabel:function(a,b){if(typeof b=="undefined")b="";return a in this.content.labels?this.content.labels[a]:
b},getCaption:function(a){a=c(a);var b="";if(this.content.caption_enabled){a={link:a,origin:a,sibs:null,img:null};if(this.itemGallery(a.link,"wp"))a.origin=c(a.link).parent();if((a.sibs=c(a.origin).siblings({capt:".wp-caption-text",gIcon:".gallery-icon"}.capt))&&c(a.sibs).length>0)b=c.trim(c(a.sibs).first().text());if(!b){a.img=c(a.link).find("img").first();if(c(a.img).length){b=c(a.img).attr("title")||c(a.img).attr("alt");b=c.trim(b)}}if(!b){b=this.mediaProp(a.link,"title")||"";b=c.trim(b)}if(!b){var d=
"";if((d=c.trim(c(a.link).text()))&&d.length)b=d;else if(this.options.captionSrc){b=c(a.link).attr("href");for(a=["/","#","."];b.length&&c.inArray(b.charAt(0),a)!=-1;)b=b.substr(1);for(;b.length&&c.inArray(b.charAt(b.length-1),a)!=-1;)b=b.substr(0,b.length-1);a=b.lastIndexOf("/");if(-1!=a)b=b.substr(a+1);a=b.lastIndexOf(".");if(-1!=a)b=b.slice(0,a)}b=c.trim(b)}}return b},getDescription:function(a){var b="";if(this.content.desc_enabled)(b=this.itemGallery(a,"ng")?c(a).attr("title"):this.mediaProp(a,
"desc"))||(b="");return b},contentUpdate:function(){if(this.content.caption_enabled){this.get("dataCaption").text(this.itemProp(this.item_curr,"title"));this.get("dataCaption").show()}else this.get("dataCaption").hide();this.get("dataDescription").html(this.itemProp(this.item_curr,"desc"));if(this.hasItems()){var a=this.getLabel("numDisplayPrefix")+" "+(this.item_curr+1)+" "+this.getLabel("numDisplaySeparator")+" "+this.items.length;this.get("dataNumber").text(a).show()}this.get("details").width(this.get("container").width());
this.navUpdate();this.get("details").animate({height:"show",opacity:"show"},650)},getLayout:function(){var a=this.layout.template,b,d;for(b in this.layout.placeholders){d="{"+b+"}";if(a.indexOf(d)!=-1){d=new RegExp(d,"g");a=a.replace(d,this.layout.placeholders[b])}}return a},setGroup:function(a){this.group=this.getGroup(a)},getGroup:function(a){if(typeof a=="undefined"||0==c(a).length)return this.group;var b="";a=c(a).attr("rel")||"";if(a!=""){var d="";d=this.addPrefix("group")+"[";var e;e=a.indexOf(d);
if(" "!=d.charAt(0)&&e>0){d=" "+d;e=a.indexOf(d)}if(e!=-1){d=c.trim(a.substring(e).replace(d,""));if(d.length>1&&d.indexOf("]")>0)b=d.substring(0,d.indexOf("]"))}}return b},inGroup:function(a){return this.hasGroup()&&this.getGroup(a)==this.getGroup()?true:false},hasGroup:function(){return c.type(this.group)=="string"&&this.group.length>0?true:false},slideshowActive:function(){return this.slideshow.active},slideshowStart:function(){this.slideshow.active=true;var a=this;clearInterval(this.slideshow.timer);
this.slideshow.timer=setInterval(function(){a.navNext();a.slideshowPause()},this.slideshow.duration*1E3);this.get("navSlideControl").text(this.getLabel("stopSlideshow"))},slideshowStop:function(){this.slideshow.active=false;this.slideshow.timer&&clearInterval(this.slideshow.timer);this.get("navSlideControl").text(this.getLabel("startSlideshow"))},slideshowToggle:function(){this.slideshowActive()?this.slideshowStop():this.slideshowStart()},slideshowPause:function(){this.slideshow.timer&&clearInterval(this.slideshow.timer)},
navUpdate:function(){if(this.hasItems()){this.get("navPrev").show();this.get("navNext").show();if(this.slideshow.enabled){this.get("navSlideControl").show();this.slideshowActive()?this.slideshowStart():this.slideshowStop()}else this.get("navSlideControl").hide()}else{this.get("dataNumber").hide();this.get("navPrev").hide();this.get("navNext").hide();this.get("navSlideControl").hide()}this.keyboardEnable()},navNext:function(){if(this.hasItems()){if(!this.slideshow.loop&&this.itemLast())return this.end();
this.itemLast()?this.navFirst():this.itemLoad(this.item_curr+1)}},navPrev:function(){if(this.hasItems()){if(!this.slideshow.loop&&this.itemFirst())return this.end();this.itemFirst()?this.navLast():this.itemLoad(this.item_curr-1)}},navFirst:function(){this.hasItems()&&this.itemLoad(0)},navLast:function(){this.hasItems()&&this.itemLoad(this.items.length-1)},keyboardEnable:function(){var a=this;c(document).keydown(function(b){a.keyboardControl(b)})},keyboardDisable:function(){c(document).unbind("keydown")},
keyboardControl:function(a){a=a.which;var b=String.fromCharCode(a).toLowerCase();if(a==27||b=="x")this.end();else if(a==39||b=="n")this.navNext();else if(a==37||b=="p")this.navPrev()},getSep:function(a){return typeof a=="undefined"?"_":a},getPrefix:function(){return this.prefix},addPrefix:function(a,b){return this.getPrefix()+this.getSep(b)+a},hasPrefix:function(a){return a.indexOf(this.addPrefix(""))===0?true:false},getID:function(a){return this.addPrefix(a)},getSel:function(a){var b="#";if(a.toString().indexOf(",")!=
-1){a=a.toString().split(",");for(b=0;b<a.length;b++)a[b]=this.getSel(c.trim(a[b]));a=a.join(",")}else{if(a in this.layout.placeholders)c(this.layout.placeholders[a]).attr("id")||(b=".");a=b+this.getID(a)}return a},get:function(a){return c(this.getSel(a))},fileExists:function(a,b,d,e){var k=this;c.isPlainObject(e)||(e=null);c.isFunction(d)||(d=function(){k.end()});c.isFunction(b)||(b=d);if(!this.options.validateLinks)return b(e);if(a in this.urls_checked)this.urls_checked[a].status<400?b(e):d(e);
else{var g=new XMLHttpRequest;g.open("HEAD",a,true);g.onreadystatechange=function(){if(4==this.readyState){k.addUrl(a,this);this.status<400?b(e):d(e)}};g.send()}},addUrl:function(a,b){a in this.urls_checked||(this.urls_checked[a]=b)}}})(jQuery);
