blank_issues_enabled: false
contact_links:
    - name: Feedback & Support
      url: https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support
      about: How to share feedback and get support for Simple Lightbox